name: Test Project

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22

    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - run: npm test

      - run: npm run build
